//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Access_rights_accounting.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Accounting_for_access_rightsEntities : DbContext
    {
        private static Accounting_for_access_rightsEntities _context; // added

        public Accounting_for_access_rightsEntities()
            : base("name=Accounting_for_access_rightsEntities")
        {
        }

        public static Accounting_for_access_rightsEntities GetContext() // Method to get the context
        {
            if (_context == null) // Check if the context is null
                _context = new Accounting_for_access_rightsEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
